import { CardProps, ImageOverflowProps, SmallCardProps } from "./type";

export const smallcardData: SmallCardProps[] = [
  { smallid: 1, smalltitle: "Card 1", smallurl: "/Assets/SmallCards/01.png" },
  { smallid: 2, smalltitle: "Card 2", smallurl: "/Assets/SmallCards/02.png" },
  { smallid: 3, smalltitle: "Card 3", smallurl: "/Assets/SmallCards/03.png" },
  { smallid: 4, smalltitle: "Card 4", smallurl: "/Assets/SmallCards/04.png" },
];

export const cardData: CardProps[] = [
  {
    id: 1,
    title: "Tristique diam a, enim, eros tellus. Viverra etiam",
    description: "Card property",
    url: "/Assets/Large/BigCard1.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 102,
   
    likes:58,
  },
  {
    id: 2,
    title: "Vulputate felis purus viverra morbi facilisi eget",
    description: "Card property",
    url: "/Assets/Large/BigCard2.png",
    price: 3.19,
    timeLeftHr: 2,
    timeLeftMin: 41,
    numberBidding: 35,
    likes:120,
  },
  {
    id: 3,
    title: "Dui accumsan leo vestibulum ornare eu",
    description: "Card property",
    url: "/Assets/Large/BigCard3.png",
    price: 1.11,
    timeLeftHr: 22,
    timeLeftMin: 59,
    numberBidding: 102,
    likes:570,
  },
  {
    id: 4,
    title: "Tristique diam a, enim, eros tellus. Viverra etiam",
    description: "Card property",
    url: "/Assets/Large/BigCard4.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 102,
    likes:58,
  },
  {
    id: 5,
    title: "Senectus adipiscing nascetur accumsan etiam",
    description: "Card property",
    url: "/Assets/Large/BigCard5.png",
    price: 1.63,
    timeLeftHr: 37,
    timeLeftMin: 1,
    numberBidding: 12,
    likes:98,
  },
  {
    id: 6,
    title: "Mattis at diam lorem nisl nam sed sociis",
    description: "Card property",
    url: "/Assets/Large/BigCard6.png",
    price: 2.55,
    timeLeftHr: 12,
    timeLeftMin: 15,
    numberBidding: 19,
    likes:58,
  },

]

export const cardData1: CardProps[] = [
  {
    id: 1,
    title: "Fames habitasse risus ultricies tortor sit",
    description: "Card property",
    url: "/Assets/Medium/MediumCard1.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 100,
    likes: 100,
  },
  {
    id: 2,
    title: "Faucibus habitasse at et platea massa mauris",
    description: "Card property",
    url: "/Assets/Medium/MediumCard2.png",
    price: 2.55,
    timeLeftHr: 22,
    timeLeftMin: 59,
    numberBidding: 101,
    likes: 100,
  },
  {
    id: 3,
    title: "Fames habitasse risus ultricies tortor sit",
    description: "Card property",
    url: "/Assets/Medium/MediumCard3.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 100,
    likes: 100,
  },
  {
    id: 4,
    title: "Fames habitasse risus ultricies tortor sit",
    description: "Card property",
    url: "/Assets/Medium/MediumCard4.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 100,
    likes: 100,
  },
  {
    id: 5,
    title: "Fames habitasse risus ultricies tortor sit",
    description: "Card property",
    url: "/Assets/Medium/MediumCard5.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 100,
    likes: 100,
  },
  {
    id: 6,
    title: "Fames habitasse risus ultricies tortor sit",
    description: "Card property",
    url: "/Assets/Medium/MediumCard6.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 100,
    likes: 100,
  },
  {
    id: 7,
    title: "Fames habitasse risus ultricies tortor sit",
    description: "Card property",
    url: "/Assets/Medium/MediumCard7.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 100,
    likes: 100,
  }
]

export const cardData2: CardProps[] = [
  {
    id: 1,
    title: "Vulputate velit viverra volutpat volutpat tristique",
    description: "Card property",
    url: "/Assets/Small/SmallCard1.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 101,
    likes: 54,
  },
  {
    id: 2,
    title: "Egestas blandit sit egestas non sed. Purus semper",
    description: "Card property",
    url: "/Assets/Small/Small1.png",
    price: 2.15,
    timeLeftHr: 22,
    timeLeftMin: 15,
    numberBidding: 101,
    likes: 54,
  },
  {
    id: 3,
    title: "Id ut consequat netus nec vel amet ut porta in augue",
    description: "Card property",
    url: "/Assets/Small/Small2.png",
    price: 2.55,
    timeLeftHr: 22,
    timeLeftMin: 15,
    numberBidding: 101,
    likes: 54,
  },

  {
    id: 4,
    title: "Sed et nibh felis integer tellus turpin",
    description: "Card property",
    url: "/Assets/Small/Small3.png",
    price: 2.55,
    timeLeftHr: 57,
    timeLeftMin: 15,
    numberBidding: 101,
    likes: 54,
  },
]

export const ImageOverflowData: ImageOverflowProps[] = [
  {
    id: 1,
    title: "Card 1",
    url: "/Assets/Overflow/image1.png",
    price: 10.99,
  },
  {
    id: 2,
    title: "Card 2",
    url: "/Assets/Overflow/image2.png",
    price: 8.99,
  },
  {
    id: 3,
    title: "Card 3",
    url: "/Assets/Overflow/image3.png",
    price: 6.99,
  },
  {
    id: 4,
    title: "Card 4",
    url: "/Assets/Overflow/image4.png",
    price: 4.99,
  },
  {
    id: 5,
    title: "Card 5",
    url: "/Assets/Overflow/Image5.png",
    price: 2.99,
  },
  {
    id: 6,
    title: "Card 6",
    url: "/Assets/Overflow/Image6.png",
    price: 1.99,
  },
  {
    id: 7,
    title: "Card 7",
    url: "/Assets/Overflow/Image7.png",
    price: 0.99,
  },
  {
    id: 8,
    title: "Card 8",
    url: "/Assets/Overflow/Image8.png",
    price: 0.49,
  },
  {
    id: 9,
    title: "Card 9",
    url: "/Assets/Overflow/image9.png",
    price: 0.29,
  }, {
    id: 10,
    title: "Card 10",
    url: "/Assets/Overflow/image10.png",
    price: 4.19,
  }, {
    id: 11,
    title: "Card 11",
    url: "/Assets/Overflow/image11.png",
    price: 3.59,
  },
  {
    id: 12,
    title: "Card 12",
    url: "/Assets/Overflow/image12.png",
    price: 2.09,
  },
  {
    id: 13,
    title: "Card 13",
    url: "/Assets/Overflow/image13.png",
    price: 2.49,
    
  },
  {
    id: 14,
    title: "Card 14",
    url: "/Assets/Overflow/image14.png",
    price: 3.99,
  },
  {
    id: 15,
    title: "Card 15",
    url: "/Assets/Overflow/image15.png",
    price: 2.99,
  },
  {
    id: 16,
    title: "Card 16",
    url: "/Assets/Overflow/image16.png",
    price: 1.99,
  },
  {
    id: 17,
    title: "Card 17",
    url: "/Assets/Overflow/image17.png",
    price : 2.29
  },

]